development:
  adapter: sqlite3
  database: db/controle_financeiro_development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: db/controle_financeiro_test.sqlite3
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: controle_financeiro_production
  pool: 5
  username: postgres
  password: postgresq1
  host: localhost
